apiVersion: v1
kind: Secret
metadata:
  name: microblog-secret
  namespace: microblog
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: example
  POSTGRES_DB: microblog
  SECRET_KEY: "you-will-never-guess"
  # Remember to change these in production!
  # Generate SECRET_KEY with: python -c "import secrets; print(secrets.token_hex(32))"
